#!/usr/bin/env bash

# Embed the FAT12 floppy image into a JavaScript file so index.html can boot
# DimOS with no file picking at all. The image is almost entirely zeroes, so
# gzip shrinks 1440 KB down to a few kilobytes that are cheap to keep in git.

set -Eeuo pipefail

readonly IMAGE="${1:-disk_img/dimos.img}"
readonly OUTPUT="${2:-web/dimos-image.js}"
readonly FLOPPY_SIZE_BYTES=1474560

if [[ ! -f "$IMAGE" ]]; then
    printf 'Image not found: %s\nRun "make iso" first.\n' "$IMAGE" >&2
    exit 1
fi

actual_size=$(wc -c < "$IMAGE" | tr -d '[:space:]')
if [[ "$actual_size" != "$FLOPPY_SIZE_BYTES" ]]; then
    printf 'Expected a %s byte floppy image, got %s bytes.\n' \
        "$FLOPPY_SIZE_BYTES" "$actual_size" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"

payload=$(gzip -9 -n -c "$IMAGE" | base64 -w0 2>/dev/null || gzip -9 -n -c "$IMAGE" | base64 | tr -d '\n')
checksum=$(sha256sum "$IMAGE" | cut -d' ' -f1)

{
    printf '// Generated by tools/embed-image.sh. Do not edit by hand.\n'
    printf '// Source: %s (%s bytes, sha256 %s)\n' "$IMAGE" "$actual_size" "$checksum"
    printf '// The launcher gunzips this back into the exact 1.44M FAT12 floppy.\n'
    printf 'window.DIMOS_EMBEDDED_IMAGE = {\n'
    printf '  size: %s,\n' "$actual_size"
    printf '  sha256: "%s",\n' "$checksum"
    printf '  gzipBase64: "%s",\n' "$payload"
    printf '};\n'
} > "$OUTPUT"

printf 'Embedded %s bytes -> %s (%s bytes of JavaScript)\n' \
    "$actual_size" "$OUTPUT" "$(wc -c < "$OUTPUT" | tr -d '[:space:]')"
